[project]
name = "cloudsmith-keyring"
version = "0.2.3"
description = "Keyring backend for Cloudsmith credentials"
readme = "README.md"
requires-python = ">=3.10"
license = "Apache-2.0"
license-files = ["LICENSE"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Security",
  "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = ["cloudsmith-cli>=1.20.1,<2", "keyring>=25.4.1"]

[build-system]
requires = ["uv_build>=0.9.17,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "keyrings.cloudsmith"

[project.entry-points."keyring.backends"]
Cloudsmith = "keyrings.cloudsmith.backend"

[project.urls]
Homepage = "https://github.com/Expensify/cloudsmith-keyring"
Issues = "https://github.com/Expensify/cloudsmith-keyring/issues"

[dependency-groups]
dev = [
    "pytest>=8.3",
    "pytest-cov>=6",
    "ruff>=0.12",
    "ty>=0.0.69",
]

[tool.ruff]
line-length = 88
target-version = "py310"

[tool.ruff.lint]
select = [
  # Flake8 rules
  "F",
  # Python errors
  "E",
  # Use flake8 quote rules.
  "Q",
  # Isort rules
  "I",
  # Disallow FIXME, TODO, etc like pylint does
  "FIX",
  # Prevent raising a bare Exception, matches pylint W0719
  "TRY002",
  # Prevent catching a bare Exception, matches pylint W0718
  "BLE001",
  # no return after else, matches pylint R1705
  "RET505",
  # no protected access, matches pylint W0212
  "SLF001",
  # Require docstrings
  "D1",
  # Unused args, matches pylint behavior
  "ARG",
  # Check for unused unpacked variables, matches part of pylint W0612
  # unused args is already covered.
  "RUF059",
  # Require path lib over os.path
  "PTH",
]
