name: Publish

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  pypi:
    name: Publish to PyPI
    runs-on: blacksmith-2vcpu-ubuntu-2404
    environment:
      name: pypi
      url: https://pypi.org/p/cloudsmith-keyring
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: useblacksmith/checkout@2d63ce5ba61677748c4e92f6eb578a8694226225 # v1.2.0
      - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          version: "0.11.32"
      - name: Build distribution
        run: uv build
      - name: Check distribution metadata
        run: uvx --from twine==6.2.0 twine check dist/*
      - name: Publish distribution
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2
